import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <nav className="flex items-center justify-between p-4">
          <div>
            <span>RelatHive</span>
          </div>
          <ul className="flex space-x-4">
            <li>
              <a href="#" className="btn btn-ghost">
                Home
              </a>
            </li>
            <li>
              <a href="#" className="btn btn-ghost">
                About
              </a>
            </li>
            <li>
              <a href="#" className="btn btn-ghost">
                Contact
              </a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
