import type { Metadata } from "next";
import { AR_One_Sans } from 'next/font/google'
import "./globals.css";
import Nav from "./components/Nav";

const arOpenSans = AR_One_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className={arOpenSans.className}>
      <body>
        <Nav />
        <main className=""> {/* Added container, margin, and padding */}
          {children}
        </main>
      </body>
    </html>
  );
}
